/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) eufs_native_dynamic_bicycle_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {15, 1, 1};
static const casadi_int casadi_s3[3] = {12, 1, 1};

/* eufs_native_dynamic_bicycle_expl_vde_adj:(i0[9],i1[9],i2[3],i3[15])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[3]? arg[3][6] : 0;
  a02=1.0000000000000000e-04;
  a03=1.;
  a04=arg[0]? arg[0][1] : 0;
  a04=(a01*a04);
  a04=(a03-a04);
  a05=(a02<=a04);
  a06=(a04<=a02);
  a06=(a06+a05);
  a05=(a05/a06);
  a06=arg[0]? arg[0][3] : 0;
  a07=arg[0]? arg[0][2] : 0;
  a08=cos(a07);
  a09=(a06*a08);
  a10=arg[0]? arg[0][4] : 0;
  a07=sin(a07);
  a11=(a10*a07);
  a09=(a09-a11);
  a02=casadi_fmax(a02,a04);
  a09=(a09/a02);
  a09=(a09/a02);
  a04=arg[1]? arg[1][0] : 0;
  a11=arg[1]? arg[1][2] : 0;
  a12=(a01*a11);
  a04=(a04-a12);
  a09=(a09*a04);
  a05=(a05*a09);
  a01=(a01*a05);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[1]? arg[1][1] : 0;
  a05=(a06*a01);
  a05=(a08*a05);
  a09=(a10*a01);
  a09=(a07*a09);
  a05=(a05-a09);
  a04=(a04/a02);
  a02=(a10*a04);
  a02=(a08*a02);
  a05=(a05-a02);
  a02=(a06*a04);
  a02=(a07*a02);
  a05=(a05-a02);
  if (res[0]!=0) res[0][2]=a05;
  a05=arg[2]? arg[2][2] : 0;
  a02=-3500.;
  a09=casadi_fmax(a05,a02);
  a12=5000.;
  a13=casadi_fmin(a09,a12);
  a14=(a13*a06);
  a14=casadi_sign(a14);
  a15=5.2631578947368363e-02;
  a16=6.6666666666666666e-06;
  a17=arg[1]? arg[1][8] : 0;
  a16=(a16*a17);
  a15=(a15*a16);
  a14=(a14*a15);
  a15=(a13*a14);
  a17=casadi_sign(a06);
  a18=1.0526315789473684e+00;
  a19=arg[1]? arg[1][7] : 0;
  a18=(a18*a19);
  a13=(a13*a18);
  a13=(a17*a13);
  a15=(a15-a13);
  a13=arg[0]? arg[0][5] : 0;
  a19=arg[1]? arg[1][4] : 0;
  a20=(a13*a19);
  a15=(a15-a20);
  a20=8.2689999999999997e-01;
  a21=(a20*a06);
  a22=1.2690355329949238e-03;
  a23=arg[1]? arg[1][3] : 0;
  a24=(a22*a23);
  a21=(a21*a24);
  a17=(a17*a21);
  a15=(a15-a17);
  a17=casadi_fabs(a06);
  a21=(a17*a24);
  a20=(a20*a21);
  a15=(a15-a20);
  a20=7.5000000000000000e-01;
  a21=(a20*a13);
  a21=(a06-a21);
  a25=(a03<=a21);
  a26=(a21<=a03);
  a26=(a26+a25);
  a25=(a25/a26);
  a26=1.8040000000000000e+00;
  a27=(a26*a13);
  a27=(a10-a27);
  a21=casadi_fmax(a03,a21);
  a27=(a27/a21);
  a28=(a27/a21);
  a29=1.2560000000000000e+01;
  a30=-5.7999999999999996e-01;
  a31=-1.3799999999999999e+00;
  a32=1.9844800000000003e+01;
  a33=atan(a27);
  a34=(a32*a33);
  a33=(a29*a33);
  a35=atan(a33);
  a35=(a30*a35);
  a34=(a34+a35);
  a35=atan(a34);
  a35=(a31*a35);
  a36=cos(a35);
  a37=1.6000000000000001e+00;
  a38=2.7500000000000002e-01;
  a39=7.7302800000000007e+03;
  a40=1.5000000000000000e+00;
  a41=(a40*a06);
  a42=(a41*a06);
  a39=(a39+a42);
  a42=(a38*a39);
  a43=2.;
  a22=(a22*a19);
  a44=(a43*a22);
  a45=6.6666666666666664e-04;
  a46=arg[1]? arg[1][5] : 0;
  a45=(a45*a46);
  a46=(a26*a45);
  a46=(a43*a46);
  a44=(a44-a46);
  a46=arg[0]? arg[0][6] : 0;
  a47=cos(a46);
  a48=2.2500000000000001e-01;
  a49=(a48*a39);
  a50=1.4760000000000000e+00;
  a51=(a50*a13);
  a51=(a10+a51);
  a51=(a51/a21);
  a52=atan(a51);
  a52=(a52-a46);
  a53=(a32*a52);
  a52=(a29*a52);
  a54=atan(a52);
  a54=(a30*a54);
  a53=(a53+a54);
  a54=atan(a53);
  a54=(a31*a54);
  a55=sin(a54);
  a55=(a37*a55);
  a56=(a49*a55);
  a57=(a47*a56);
  a35=sin(a35);
  a35=(a37*a35);
  a58=(a42*a35);
  a57=(a57+a58);
  a57=(a43*a57);
  a58=(a57+a57);
  a39=(a37*a39);
  a59=casadi_sq(a39);
  a57=casadi_sq(a57);
  a59=(a59-a57);
  a57=(a03<=a59);
  a60=(a59<=a03);
  a60=(a60+a57);
  a57=(a57/a60);
  a59=casadi_fmax(a03,a59);
  a59=sqrt(a59);
  a60=788.;
  a61=arg[2]? arg[2][1] : 0;
  a61=(a60*a61);
  a62=(-a59);
  a63=casadi_fmax(a61,a62);
  a64=casadi_fmin(a63,a59);
  a65=casadi_fmax(a64,a62);
  a66=(a59<=a65);
  a65=(a65<=a59);
  a67=(a65+a66);
  a66=(a66/a67);
  a66=(a66*a24);
  a68=(a64<=a62);
  a64=(a62<=a64);
  a69=(a64+a68);
  a68=(a68/a69);
  a65=(a65/a67);
  a65=(a65*a24);
  a68=(a68*a65);
  a66=(a66-a68);
  a68=(a59<=a63);
  a63=(a63<=a59);
  a67=(a63+a68);
  a68=(a68/a67);
  a64=(a64/a69);
  a64=(a64*a65);
  a68=(a68*a64);
  a66=(a66+a68);
  a68=(a61<=a62);
  a62=(a62<=a61);
  a61=(a62+a68);
  a68=(a68/a61);
  a63=(a63/a67);
  a63=(a63*a64);
  a68=(a68*a63);
  a66=(a66-a68);
  a59=(a59+a59);
  a66=(a66/a59);
  a57=(a57*a66);
  a58=(a58*a57);
  a58=(a43*a58);
  a44=(a44-a58);
  a42=(a42*a44);
  a42=(a37*a42);
  a36=(a36*a42);
  a36=(a31*a36);
  a34=casadi_sq(a34);
  a34=(a03+a34);
  a36=(a36/a34);
  a34=(a30*a36);
  a33=casadi_sq(a33);
  a33=(a03+a33);
  a34=(a34/a33);
  a34=(a29*a34);
  a36=(a32*a36);
  a34=(a34+a36);
  a27=casadi_sq(a27);
  a27=(a03+a27);
  a34=(a34/a27);
  a28=(a28*a34);
  a27=(a51/a21);
  a54=cos(a54);
  a36=(a43*a47);
  a45=(a50*a45);
  a33=(a36*a45);
  a36=(a36*a22);
  a33=(a33+a36);
  a36=sin(a46);
  a42=(a43*a36);
  a42=(a42*a24);
  a33=(a33-a42);
  a42=(a47*a58);
  a33=(a33-a42);
  a49=(a49*a33);
  a49=(a37*a49);
  a54=(a54*a49);
  a31=(a31*a54);
  a53=casadi_sq(a53);
  a53=(a03+a53);
  a31=(a31/a53);
  a30=(a30*a31);
  a52=casadi_sq(a52);
  a52=(a03+a52);
  a30=(a30/a52);
  a29=(a29*a30);
  a32=(a32*a31);
  a29=(a29+a32);
  a51=casadi_sq(a51);
  a03=(a03+a51);
  a03=(a29/a03);
  a27=(a27*a03);
  a28=(a28+a27);
  a25=(a25*a28);
  a15=(a15-a25);
  a35=(a35*a44);
  a38=(a38*a35);
  a55=(a55*a33);
  a48=(a48*a55);
  a38=(a38+a48);
  a39=(a39+a39);
  a39=(a39*a57);
  a37=(a37*a39);
  a38=(a38+a37);
  a41=(a41*a38);
  a15=(a15+a41);
  a38=(a06*a38);
  a40=(a40*a38);
  a15=(a15+a40);
  a40=(a07*a01);
  a15=(a15+a40);
  a40=(a08*a04);
  a15=(a15+a40);
  if (res[0]!=0) res[0][3]=a15;
  a34=(a34/a21);
  a03=(a03/a21);
  a21=(a34+a03);
  a13=(a13*a23);
  a21=(a21+a13);
  a08=(a08*a01);
  a21=(a21+a08);
  a07=(a07*a04);
  a21=(a21-a07);
  if (res[0]!=0) res[0][4]=a21;
  a20=(a20*a25);
  a19=(a06*a19);
  a26=(a26*a34);
  a19=(a19+a26);
  a20=(a20-a19);
  a50=(a50*a03);
  a20=(a20+a50);
  a10=(a10*a23);
  a20=(a20+a10);
  a20=(a20+a11);
  if (res[0]!=0) res[0][5]=a20;
  a58=(a56*a58);
  a58=(a36*a58);
  a20=5.;
  a11=-1.2916000000000001e+00;
  a10=arg[2]? arg[2][0] : 0;
  a23=-6.4580000000000004e-01;
  a50=casadi_fmax(a10,a23);
  a03=6.4580000000000004e-01;
  a19=casadi_fmin(a50,a03);
  a19=(a19-a46);
  a46=2.0000000000000001e-01;
  a19=(a19/a46);
  a46=(a11<=a19);
  a26=(a19<=a11);
  a26=(a46+a26);
  a46=(a46/a26);
  a19=casadi_fmax(a19,a11);
  a11=1.2916000000000001e+00;
  a26=(a19<=a11);
  a11=(a11<=a19);
  a11=(a26+a11);
  a26=(a26/a11);
  a11=arg[1]? arg[1][6] : 0;
  a26=(a26*a11);
  a46=(a46*a26);
  a20=(a20*a46);
  a45=(a56*a45);
  a45=(a43*a45);
  a45=(a36*a45);
  a45=(a20+a45);
  a22=(a56*a22);
  a22=(a43*a22);
  a36=(a36*a22);
  a45=(a45+a36);
  a56=(a56*a24);
  a43=(a43*a56);
  a47=(a47*a43);
  a45=(a45+a47);
  a45=(a45+a29);
  a58=(a58-a45);
  if (res[0]!=0) res[0][6]=a58;
  if (res[0]!=0) res[0][7]=a00;
  a00=100.;
  a00=(a00*a16);
  a00=(-a00);
  if (res[0]!=0) res[0][8]=a00;
  a00=(a23<=a10);
  a10=(a10<=a23);
  a10=(a00+a10);
  a00=(a00/a10);
  a10=(a50<=a03);
  a03=(a03<=a50);
  a03=(a10+a03);
  a10=(a10/a03);
  a10=(a10*a20);
  a00=(a00*a10);
  if (res[0]!=0) res[0][9]=a00;
  a62=(a62/a61);
  a62=(a62*a63);
  a60=(a60*a62);
  if (res[0]!=0) res[0][10]=a60;
  a60=(a02<=a05);
  a05=(a05<=a02);
  a05=(a60+a05);
  a60=(a60/a05);
  a05=(a09<=a12);
  a12=(a12<=a09);
  a12=(a05+a12);
  a05=(a05/a12);
  a06=(a06*a14);
  a17=(a17*a18);
  a06=(a06-a17);
  a05=(a05*a06);
  a60=(a60*a05);
  if (res[0]!=0) res[0][11]=a60;
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eufs_native_dynamic_bicycle_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int eufs_native_dynamic_bicycle_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real eufs_native_dynamic_bicycle_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eufs_native_dynamic_bicycle_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eufs_native_dynamic_bicycle_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eufs_native_dynamic_bicycle_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eufs_native_dynamic_bicycle_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
