/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) eufs_native_dynamic_bicycle_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {15, 1, 1};

/* eufs_native_dynamic_bicycle_expl_ode_fun:(i0[9],i1[3],i2[15])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][4] : 0;
  a01=sin(a01);
  a05=(a04*a01);
  a03=(a03-a05);
  a05=1.0000000000000000e-04;
  a06=1.;
  a07=arg[2]? arg[2][6] : 0;
  a08=arg[0]? arg[0][1] : 0;
  a08=(a07*a08);
  a08=(a06-a08);
  a05=casadi_fmax(a05,a08);
  a03=(a03/a05);
  if (res[0]!=0) res[0][0]=a03;
  a01=(a00*a01);
  a02=(a04*a02);
  a01=(a01+a02);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[0]? arg[0][5] : 0;
  a07=(a07*a03);
  a07=(a01-a07);
  if (res[0]!=0) res[0][2]=a07;
  a07=(a01*a04);
  a03=788.;
  a02=arg[1]? arg[1][1] : 0;
  a02=(a03*a02);
  a05=1.6000000000000001e+00;
  a08=7.7302800000000007e+03;
  a09=1.5000000000000000e+00;
  a09=(a09*a00);
  a09=(a09*a00);
  a08=(a08+a09);
  a09=(a05*a08);
  a09=casadi_sq(a09);
  a10=2.;
  a11=arg[0]? arg[0][6] : 0;
  a12=cos(a11);
  a13=2.2500000000000001e-01;
  a13=(a13*a08);
  a14=-1.3799999999999999e+00;
  a15=1.9844800000000003e+01;
  a16=1.4760000000000000e+00;
  a17=(a16*a01);
  a17=(a04+a17);
  a18=7.5000000000000000e-01;
  a18=(a18*a01);
  a18=(a00-a18);
  a18=casadi_fmax(a06,a18);
  a17=(a17/a18);
  a17=atan(a17);
  a17=(a17-a11);
  a19=(a15*a17);
  a20=-5.7999999999999996e-01;
  a21=1.2560000000000000e+01;
  a17=(a21*a17);
  a17=atan(a17);
  a17=(a20*a17);
  a19=(a19+a17);
  a19=atan(a19);
  a19=(a14*a19);
  a19=sin(a19);
  a19=(a05*a19);
  a13=(a13*a19);
  a19=(a12*a13);
  a17=2.7500000000000002e-01;
  a17=(a17*a08);
  a08=1.8040000000000000e+00;
  a22=(a08*a01);
  a04=(a04-a22);
  a04=(a04/a18);
  a04=atan(a04);
  a15=(a15*a04);
  a21=(a21*a04);
  a21=atan(a21);
  a20=(a20*a21);
  a15=(a15+a20);
  a15=atan(a15);
  a14=(a14*a15);
  a14=sin(a14);
  a05=(a05*a14);
  a17=(a17*a05);
  a19=(a19+a17);
  a19=(a10*a19);
  a19=casadi_sq(a19);
  a09=(a09-a19);
  a06=casadi_fmax(a06,a09);
  a06=sqrt(a06);
  a09=(-a06);
  a02=casadi_fmax(a02,a09);
  a02=casadi_fmin(a02,a06);
  a02=casadi_fmax(a02,a09);
  a02=casadi_fmin(a02,a06);
  a06=8.2689999999999997e-01;
  a06=(a06*a00);
  a09=casadi_fabs(a00);
  a06=(a06*a09);
  a19=120.;
  a06=(a06+a19);
  a02=(a02-a06);
  a06=sin(a11);
  a06=(a10*a06);
  a06=(a06*a13);
  a02=(a02-a06);
  a02=(a02/a03);
  a07=(a07+a02);
  if (res[0]!=0) res[0][3]=a07;
  a12=(a10*a12);
  a12=(a12*a13);
  a10=(a10*a17);
  a17=(a12+a10);
  a17=(a17/a03);
  a01=(a01*a00);
  a17=(a17-a01);
  if (res[0]!=0) res[0][4]=a17;
  a16=(a16*a12);
  a08=(a08*a10);
  a16=(a16-a08);
  a08=1500.;
  a16=(a16/a08);
  if (res[0]!=0) res[0][5]=a16;
  a16=arg[1]? arg[1][0] : 0;
  a08=-6.4580000000000004e-01;
  a16=casadi_fmax(a16,a08);
  a08=6.4580000000000004e-01;
  a16=casadi_fmin(a16,a08);
  a16=(a16-a11);
  a11=2.0000000000000001e-01;
  a16=(a16/a11);
  a11=-1.2916000000000001e+00;
  a16=casadi_fmax(a16,a11);
  a11=1.2916000000000001e+00;
  a16=casadi_fmin(a16,a11);
  if (res[0]!=0) res[0][6]=a16;
  a16=arg[1]? arg[1][2] : 0;
  a11=-3500.;
  a16=casadi_fmax(a16,a11);
  a11=5000.;
  a16=casadi_fmin(a16,a11);
  a09=(a16*a09);
  a11=9.4999999999999996e-01;
  a09=(a09/a11);
  a11=500.;
  a09=(a09+a11);
  a09=(-a09);
  if (res[0]!=0) res[0][7]=a09;
  a09=5.2631578947368363e-02;
  a16=(a16*a00);
  a16=casadi_fabs(a16);
  a09=(a09*a16);
  a09=(a09+a11);
  a11=100.;
  a16=arg[0]? arg[0][8] : 0;
  a00=2.9814999999999998e+02;
  a16=(a16-a00);
  a11=(a11*a16);
  a09=(a09-a11);
  a11=150000.;
  a09=(a09/a11);
  if (res[0]!=0) res[0][8]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eufs_native_dynamic_bicycle_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int eufs_native_dynamic_bicycle_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real eufs_native_dynamic_bicycle_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eufs_native_dynamic_bicycle_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eufs_native_dynamic_bicycle_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eufs_native_dynamic_bicycle_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eufs_native_dynamic_bicycle_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
