/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {15, 1, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[18] = 
  {12, 5, 0, 5, 6, 7, 8, 10,
  1, 6, 7, 8, 9, 4, 4, 10,
  2, 6};
static const casadi_int casadi_s6[3] = {5, 0, 1};

/* eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt:(i0[9],i1[3],i2[0],i3[15])->(o0[5],o1[12x5,10nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39;
  a00=1.6000000000000001e+00;
  a01=7.7302800000000007e+03;
  a02=1.5000000000000000e+00;
  a03=arg[0]? arg[0][3] : 0;
  a04=(a02*a03);
  a05=(a04*a03);
  a01=(a01+a05);
  a05=(a00*a01);
  a06=casadi_sq(a05);
  a07=788.;
  a08=arg[1]? arg[1][1] : 0;
  a08=(a07*a08);
  a09=casadi_sq(a08);
  a06=(a06-a09);
  a09=2.;
  a10=arg[0]? arg[0][6] : 0;
  a11=cos(a10);
  a12=2.2500000000000001e-01;
  a13=(a12*a01);
  a14=-1.3799999999999999e+00;
  a15=1.9844800000000003e+01;
  a16=arg[0]? arg[0][4] : 0;
  a17=1.4760000000000000e+00;
  a18=arg[0]? arg[0][5] : 0;
  a19=(a17*a18);
  a19=(a16+a19);
  a20=1.;
  a21=7.5000000000000000e-01;
  a22=(a21*a18);
  a22=(a03-a22);
  a23=casadi_fmax(a20,a22);
  a19=(a19/a23);
  a24=atan(a19);
  a24=(a24-a10);
  a25=(a15*a24);
  a26=-5.7999999999999996e-01;
  a27=1.2560000000000000e+01;
  a24=(a27*a24);
  a28=atan(a24);
  a28=(a26*a28);
  a25=(a25+a28);
  a28=atan(a25);
  a28=(a14*a28);
  a29=sin(a28);
  a29=(a00*a29);
  a30=(a13*a29);
  a31=(a11*a30);
  a32=2.7500000000000002e-01;
  a01=(a32*a01);
  a33=1.8040000000000000e+00;
  a18=(a33*a18);
  a16=(a16-a18);
  a16=(a16/a23);
  a18=atan(a16);
  a34=(a15*a18);
  a18=(a27*a18);
  a35=atan(a18);
  a35=(a26*a35);
  a34=(a34+a35);
  a35=atan(a34);
  a35=(a14*a35);
  a36=sin(a35);
  a36=(a00*a36);
  a37=(a01*a36);
  a31=(a31+a37);
  a31=(a09*a31);
  a37=casadi_sq(a31);
  a06=(a06-a37);
  if (res[0]!=0) res[0][0]=a06;
  a06=arg[0]? arg[0][1] : 0;
  a37=arg[3]? arg[3][10] : 0;
  a38=1.0500000000000000e+00;
  a37=(a37+a38);
  a37=(a06-a37);
  if (res[0]!=0) res[0][1]=a37;
  a37=arg[3]? arg[3][11] : 0;
  a37=(a37-a38);
  a37=(a37-a06);
  if (res[0]!=0) res[0][2]=a37;
  a37=arg[0]? arg[0][7] : 0;
  a06=arg[3]? arg[3][12] : 0;
  a37=(a37-a06);
  if (res[0]!=0) res[0][3]=a37;
  a37=120000.;
  a06=arg[1]? arg[1][2] : 0;
  a38=(a06*a03);
  a39=casadi_fabs(a38);
  a37=(a37-a39);
  if (res[0]!=0) res[0][4]=a37;
  a08=(a08+a08);
  a07=(a07*a08);
  a07=(-a07);
  if (res[1]!=0) res[1][0]=a07;
  a07=(a20<=a22);
  a22=(a22<=a20);
  a22=(a22+a07);
  a07=(a07/a22);
  a22=(a16/a23);
  a35=cos(a35);
  a31=(a31+a31);
  a09=(a09*a31);
  a01=(a01*a09);
  a01=(a00*a01);
  a35=(a35*a01);
  a35=(a14*a35);
  a34=casadi_sq(a34);
  a34=(a20+a34);
  a35=(a35/a34);
  a34=(a26*a35);
  a18=casadi_sq(a18);
  a18=(a20+a18);
  a34=(a34/a18);
  a34=(a27*a34);
  a35=(a15*a35);
  a34=(a34+a35);
  a16=casadi_sq(a16);
  a16=(a20+a16);
  a34=(a34/a16);
  a22=(a22*a34);
  a16=(a19/a23);
  a28=cos(a28);
  a11=(a11*a09);
  a13=(a13*a11);
  a13=(a00*a13);
  a28=(a28*a13);
  a14=(a14*a28);
  a25=casadi_sq(a25);
  a25=(a20+a25);
  a14=(a14/a25);
  a26=(a26*a14);
  a24=casadi_sq(a24);
  a24=(a20+a24);
  a26=(a26/a24);
  a27=(a27*a26);
  a15=(a15*a14);
  a27=(a27+a15);
  a19=casadi_sq(a19);
  a19=(a20+a19);
  a19=(a27/a19);
  a16=(a16*a19);
  a22=(a22+a16);
  a07=(a07*a22);
  a05=(a05+a05);
  a00=(a00*a05);
  a36=(a36*a09);
  a32=(a32*a36);
  a29=(a29*a11);
  a12=(a12*a29);
  a32=(a32+a12);
  a00=(a00-a32);
  a04=(a04*a00);
  a04=(a07+a04);
  a00=(a03*a00);
  a02=(a02*a00);
  a04=(a04+a02);
  if (res[1]!=0) res[1][1]=a04;
  a34=(a34/a23);
  a19=(a19/a23);
  a23=(a34+a19);
  a23=(-a23);
  if (res[1]!=0) res[1][2]=a23;
  a33=(a33*a34);
  a21=(a21*a07);
  a33=(a33-a21);
  a17=(a17*a19);
  a33=(a33-a17);
  if (res[1]!=0) res[1][3]=a33;
  a10=sin(a10);
  a30=(a30*a09);
  a10=(a10*a30);
  a27=(a27+a10);
  if (res[1]!=0) res[1][4]=a27;
  if (res[1]!=0) res[1][5]=a20;
  a27=-1.;
  if (res[1]!=0) res[1][6]=a27;
  if (res[1]!=0) res[1][7]=a20;
  a38=casadi_sign(a38);
  a03=(a03*a38);
  a03=(-a03);
  if (res[1]!=0) res[1][8]=a03;
  a06=(a06*a38);
  a06=(-a06);
  if (res[1]!=0) res[1][9]=a06;
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int eufs_native_dynamic_bicycle_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
